### ISSUE TITLE
Having trouble pre-training with example code

### ISSUE THREAD

**Issue by Data-reindeer** [HannesStark/self-supervised-graphs#4]
Hi,
After installing all the required packages, I follow the Step 2 in Readme.md to run the following code:
> python train.py --config=configs_clean/pre-train_QM9.yml

However,  I got the error as follow:
Traceback (most recent call last):
  File "train.py", line 699, in <module>
    train(args)
  File "train.py", line 270, in train
    return train_qm9(args, device, metrics_dict)
  File "train.py", line 562, in train_qm9
    dist_embedding=args.dist_embedding, num_radial=args.num_radial)
  File "/data2/3DInfomax/datasets/qm9_dataset.py", line 187, in __init__
    self.dist_embedder = dist_emb(num_radial=6).to(device)
  File "/data2/3DInfomax/commons/spherical_encoding.py", line 183, in __init__
    self.reset_parameters()
  File "/data2/3DInfomax/commons/spherical_encoding.py", line 186, in reset_parameters
    torch.arange(1, self.freq.numel() + 1, out=self.freq).mul_(PI)
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

I didn't modify the code. Any idea for aforementioned error?

**Comment by HannesStark** [comment]
Hi dear reindeer,

I am not exactly sure why this error is not occurring for me, but this functionality is no longer used anywhere else in the code so I just removed it. 

If you pull the most recent changes it should work.
Please let me know if you have any other issues!

**Comment by Data-reindeer** [comment]
Thank you for your propmt reply! But there is another error：
File "train.py", line 700, in <module>
    train(args)
  File "train.py", line 272, in train
    return train_qm9(args, device, metrics_dict)
  File "train.py", line 608, in train_qm9
    val_metrics = trainer.train(train_loader, val_loader)
  File "/data2/3DInfomax/trainer/trainer.py", line 73, in train
    self.predict(train_loader, epoch, optim=self.optim)
  File "/data2/3DInfomax/trainer/trainer.py", line 135, in predict
    for i, batch in enumerate(data_loader):
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/env1/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 363, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/data2/3DInfomax/datasets/qm9_dataset.py", line 201, in __getitem__
    e_start = self.meta_dict['edge_slices'][idx].item()
IndexError: index 69600 is out of bounds for dimension 0 with size 30

**Comment by HannesStark** [comment]
Thanks for pointing that out!
That was caused by some debugging code that I introduced recently and then did not cause any issues for me because I already had the preprocessed data.

I now tested everything with a new clone of the repository, and after removing the old debugging code it worked.
The changes are in the latest commit. 
Sorry for the inconvenience!

**Comment by Data-reindeer** [comment]
The latest version works well. 
Thanks a lot !
