### ISSUE TITLE
Fine-tuning a model with `BACEGeomol` dataset - error when collating

### ISSUE THREAD

**Issue by davidfarinajr** [HannesStark/self-supervised-graphs#6]
Hello, I am trying to fine-tune the pre-trained model you provided here `runs/PNA_qmugs_NTXentMultiplePositives_620000_123_25-08_09-19-52/best_checkpoint_35epochs.pt` with a csv of the bace dataset.  When I use the `BACEGeomol` class to load and process the data, I get the following error when trying to collate the data with `torch_geometric`.

```
Traceback (most recent call last):
  File "train.py", line 702, in <module>
    train(args)
  File "train.py", line 286, in train
    return train_geomol(args, device, metrics_dict)
  File "train.py", line 313, in train_geomol
    train = dataset(split='train', device=device)
  File "/home/ubuntu/code/3DInfomax/datasets/bace_geomol_feat.py", line 59, in __init__
    super(BACEGeomol, self).__init__(root, transform, pre_transform)
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 88, in __init__
    self._process()
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 171, in _process
    self.process()
  File "/home/ubuntu/code/3DInfomax/datasets/bace_geomol_feat.py", line 127, in process
    data, slices = self.collate(data_list)
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 116, in collate
    add_batch=False,
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 85, in collate
    increment)
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 179, in _collate
    key, [v[key] for v in values], data_list, stores, increment)
  File "/home/ubuntu/anaconda3/envs/3DInfomax/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 179, in <listcomp>
    key, [v[key] for v in values], data_list, stores, increment)
KeyError: 0
```

My questions are: 
1) I see there are a lot of different dataset classes.  Can I use the `BACEGeomol` dataset class to fine-tune that model, or should I be using a different dataset class?  I'm also not sure because I see different functions to featurize molecules in the different classes.
2) Have you seen this error before, and do you know what might be causing the bug?

Thank you!

**Comment by HannesStark** [comment]
Hi David!
To finetune the model you need to use the same featurization that was used during pre-training.

An example to fine-tune the weights you were looking at, you can look at `configs_clean/tune_freesolv.yml`.

If you instead want to fine-tune with the BACE dataset, you can switch `dataset: 'ogbg-molfreesolv'` with `dataset: 'ogbg-molbace'`

The `BACEGeomol` dataset uses the featurization of Geomol instead.

Let me know if that answers everything!

**Comment by davidfarinajr** [comment]
Hi Hannes!  I'm trying to fine-tune the model for classification on a csv of bace data with `smiles` and `class` columns. I don't think I can use the `OGBGDatasetExtension` dataset since I need a function to featurize from smiles and make dgl graphs.  I would need something similar to the `process` and `get_graph` methods of the `QM9Dataset` class.  Which dataset class would you recommend for this purpose?  I am anticipating that I may need to tweak it a little to work with my data, but if you could point for the best place for me to start, that would be a huge help.

Thanks!
David

**Comment by HannesStark** [comment]
Hey,
The simples would be tweaking the inference_dataset.py for that purpose!

**Comment by davidfarinajr** [comment]
Thanks! I will give that a try
